In [12]:
import numpy as np

#1 Tạo array arr có kích thước 3x3 với các giá trị True
arr = np.array([[True, True, True],
                [True, True, True],
                [True, True, True]])
print("Ma trận có kích thước 3x3:")
print(arr)

#2 Tạo arr_1D có kích thước 9 và sau đó chuyển đổi thành arr_2D với kích thước 3x3
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
ma_tran = arr_1D.reshape((3, 3))
# In ra ma trận ban đầu
print("Ma trận ban đầu:")
print(ma_tran)

#a Hoán đổi cột 1 và cột 3
ma_tran[:, [0, 2]] = ma_tran[:, [2, 0]]
arr_2D = ma_tran
print("Ma trận sau khi hoán đổi cột 1 và cột 3:")
print(arr_2D)

#b Để hoán đổi cột 3 và cột 1 lần nữa, ta có thể lặp lại quá trình
ma_tran[:, [2, 0]] = ma_tran[:, [0, 2]]
print("Ma trận sau khi hoán đổi lại cột 1 và cột 3:")
print(ma_tran)

#3 Chuyển dòng 1 sang dòng 2 và ngược lại 
# Hoán đổi dòng 1 và dòng 2
arr_2D[[0, 1]] = arr_2D[[1, 0],:]
print("Ma trận sau khi hoán đổi dòng 1 và dòng 2:")
print(arr_2D)

#Ngược lại 
# Hoán đổi dòng 2 và dòng 1
arr_2D[[1,0]] = arr_2D[[0,1]]
print("Ma trận sau khi hoán đổi dòng 2 và dòng 1:")
print(arr_2D)

#4 Đảo ngược các dòng của arr_2D
arr_2D_dao_nguoc_dong = arr_2D[::-1,:]
print("Đảo ngược dòng của arr_2D:")
print(arr_2D_dao_nguoc_dong)

# 5 Đảo ngược các cột của arr_2D
arr_2D_dao_nguoc_cot = arr_2D[:, ::-1]
print("Đảo ngược cột của arr_2D:")
print(arr_2D_dao_nguoc_cot)

#6 Kiểm tra trong array có giá trị rỗng không ?
arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]])
print("\n6. Array with null values:")
print(arr_2D_null)
print("Kiểm tra trong array có giá trị rỗng không?")
empty_values = np.isNaNN(arr_2D_null)
for i in range(arr_2D_null.shape[0]):
    for j in range(arr_2D_null.shape[1]):
        if empty_values[i, j]:
            print(f"Giá trị rỗng tại vị trí [{i}, {j}]")

# 7. Replace null values with 0
arr_2D_null[np.isnan(arr_2D_null)] = 0
print("\n7. After replacing null values with 0:")
print(arr_2D_null)

Ma trận có kích thước 3x3:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
Ma trận ban đầu:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Ma trận sau khi hoán đổi cột 1 và cột 3:
[[2 1 0]
 [5 4 3]
 [8 7 6]]
Ma trận sau khi hoán đổi lại cột 1 và cột 3:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Ma trận sau khi hoán đổi dòng 1 và dòng 2:
[[3 4 5]
 [0 1 2]
 [6 7 8]]
Ma trận sau khi hoán đổi dòng 2 và dòng 1:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Đảo ngược dòng của arr_2D:
[[6 7 8]
 [3 4 5]
 [0 1 2]]
Đảo ngược cột của arr_2D:
[[2 1 0]
 [5 4 3]
 [8 7 6]]


AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.